import Head from 'next/head'



export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       <h1 style={{textAlign:"center"}}>Welcome Users</h1>
      <div style={{background:"blue",height:"30px",width:"110px",borderRadius:"25px",marginLeft:"625px"}}>
      <a href='/login' style={{color:"white",fontSize:"25px",textDecoration:"none",marginLeft:"7px"}}>Get Start</a>
      </div>
   
    </>
  )
}
